// ng/src/app/components/signup/signup.component.ts
import { Component, OnInit } from '@angular/core';
import { ApiService } from '../../services/api.service';
import { NotificationService } from '../../services/notification.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css']
})
export class SignupComponent implements OnInit {

  name: string;
  phone: string;
  password: string;

  constructor(private api: ApiService,
    private notifications: NotificationService,
    private router: Router) { }

  ngOnInit() {
  }

  submit() {
    this.api.register(this.name, this.phone, this.password).subscribe(
      data => {
        if (data.success) {
          this.router.navigateByUrl('/dashboard');
        }
        else {
          console.log(data);

          this.notifications.show(data.msg);
        }
      }
    );
  }
}

<div class="card mat-elevation-z1 bg-white">
  <div class="card-body">
    <form (ngSubmit)="submit()" #regForm="ngForm">

      <br>

      <h1 class="display-4 text-center">Register</h1>
      
      <br>

      <div class="form-group">
        <label>Name</label>

        <input type="text" class="form-control" placeholder="Enter Name" [(ngModel)]="name" name="name" required #nameField="ngModel">
        <div *ngIf="nameField.invalid && (nameField.dirty || nameField.touched)" class="text-danger">
          <div *ngIf="nameField.errors.required">
            Name is required.
          </div>
          <br>
        </div>
      </div>

      <div class="form-group">
        <label>Phone</label>

        <input type="text" class="form-control" placeholder="Enter Phone" [(ngModel)]="phone" name="phone" required #phoneField="ngModel">
        <div *ngIf="phoneField.invalid && (phoneField.dirty || phoneField.touched)" class="text-danger">
          <div *ngIf="phoneField.errors.required">
            Phone is required.
          </div>
          <br>
        </div>
      </div>

      <div class="form-group">
        <label for="password">Password</label>

        <input type="password" class="form-control" id="password" placeholder="Enter Password" [(ngModel)]="password" name="password" required #passwordField="ngModel">
        <div *ngIf="passwordField.invalid && (passwordField.dirty || passwordField.touched)" class="text-danger">
          <div *ngIf="passwordField.errors.required">
            Password is required.
          </div>
          <br>
        </div>
      </div>

      <br>
      
      <button class="btn btn-primary btn-block" [disabled]="!regForm.form.valid">Register</button>

      <br>

      <div class="text-center text-muted">
        Already have an account?, <a routerLink="/login">Login</a>
      </div>
  
      <br>
    </form>
  </div>
</div>

// react/src/components/Signup.js
import React, { Component } from 'react';
import './Login.css';

class Signup extends Component {
  render() {
    return (
      <div className="card card-center mat-elevation-z1 bg-white">
        <div className="card-body">
          <form>
            <br/>

            <h1 className="display-4 text-center">Signup</h1>

            <br/>

            <div className="form-group">
              <label>Name</label>

              <input type="text" className="form-control" placeholder="Enter Name" name="name" required/>
            </div>

            <div className="form-group">
              <label>Phone</label>

              <input type="tel" className="form-control" placeholder="Enter Phone Number" name="phone" required/>
            </div>

            <div className="form-group">
              <label>Password</label>

              <input type="password" className="form-control" placeholder="Enter Password" name="password" required/>
            </div>

            <br/>

            <button className="btn btn-primary btn-block">Signup</button>

            <br/>
          </form>
        </div>
      </div>
    );
  }
}

export default Signup;
