// react/src/components/Login.js
import React, { Component } from 'react';
import "./Login.css";

class Login extends Component {
  render() {
    return (
      <div className="card card-center mat-elevation-z1 bg-white">
        <div className="card-body">
          <form>
            <br/>

            <h1 className="display-4 text-center">Login</h1>

            <br/>

            <div className="form-group">
              <label>Phone</label>

              <input type="tel" className="form-control" placeholder="Enter Phone Number" name="phone" required/>
            </div>

            <div className="form-group">
              <label>Password</label>

              <input type="password" className="form-control" placeholder="Enter Password" name="password" required/>
            </div>

            <br/>

            <button className="btn btn-primary btn-block">Login</button>

            <br/>
          </form>
        </div>
      </div>
    );
  }
}

export default Login;

// ng/src/app/components/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { NotificationService } from '../../services/notification.service';
import { ApiService } from '../../services/api.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  phone: string;
  password: string;

  constructor(private api: ApiService,
    private notifications: NotificationService,
    private router: Router) { }

  ngOnInit() {
  }

  submit() {
    this.api.login(this.phone, this.password).subscribe(
      data => {
        if (data.success) {
          this.router.navigateByUrl('/dashboard');
        }
        else {
          console.log(data);

          this.notifications.show(data.msg);
        }
      }
    );
  }
}

<div class="card mat-elevation-z1 bg-white">
  <div class="card-body">
    <form (ngSubmit)="submit()" #loginForm="ngForm">

      <br>

      <h1 class="display-4 text-center">Login</h1>
      
      <br>

      <div class="form-group">
        <label>Phone</label>

        <input type="text" class="form-control" placeholder="Enter Phone" [(ngModel)]="phone" name="phone" required #phoneField="ngModel">
        <div *ngIf="phoneField.invalid && (phoneField.dirty || phoneField.touched)" class="text-danger">
          <div *ngIf="phoneField.errors.required">
            Phone is required.
          </div>
          <br>
        </div>
      </div>

      <div class="row">
        <div class="col">
          <label>Password</label>
        </div>
        <div class="col-auto small">
          <a routerLink="/forgotPassword">Forgot Password?</a>
        </div>
      </div>

      <div class="form-group">
        <input type="password" class="form-control" placeholder="Enter Password" [(ngModel)]="password" name="password" required #passwordField="ngModel">
        <div *ngIf="passwordField.invalid && (passwordField.dirty || passwordField.touched)" class="text-danger">
          <div *ngIf="passwordField.errors.required">
            Password is required.
          </div>
          <br>
        </div>
      </div>

      <br>
      
      <button class="btn btn-primary btn-block" [disabled]="!loginForm.form.valid">Login</button>

      <br>

      <div class="text-center text-muted">
        Don't have an account?, <a routerLink="/register">Register</a>
      </div>
  
      <br>
    </form>
  </div>
</div>
